### ISSUE TITLE
Causes RuntimeError: Working outside of application context

### ISSUE THREAD

**Issue by olliebreeden** [steinitzu/spoffy#3]
When applied to my celery tasks, it causes a RuntimeError, traceback below:

celery_1   | Traceback (most recent call last):
celery_1   |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
celery_1   |     R = retval = fun(*args, **kwargs)
celery_1   |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
celery_1   |     return self.run(*args, **kwargs)
celery_1   |   File "/carinfo/src/blueprints/cars/tasks.py", line 35, in get_car_image
celery_1   |     Car_image.get_api_image(car_id)
celery_1   |   File "/carinfo/src/blueprints/cars/models/car_image.py", line 125, in get_api_image
celery_1   |     Car_image.add(image_url, car, priority=3)
celery_1   |   File "/carinfo/src/blueprints/cars/models/car_image.py", line 93, in add
celery_1   |     return Car_image.save_new_image(file, car.id, user_id, priority)
celery_1   |   File "/carinfo/src/blueprints/cars/models/car_image.py", line 99, in save_new_image
celery_1   |     image_filename = images.save(file, "car_image")
celery_1   |   File "/usr/local/lib/python3.7/site-packages/flask_uploads.py", line 414, in save
celery_1   |     if not self.file_allowed(storage, basename):
celery_1   |   File "/usr/local/lib/python3.7/site-packages/flask_uploads.py", line 370, in file_allowed
celery_1   |     return self.extension_allowed(extension(basename))
celery_1   |   File "/usr/local/lib/python3.7/site-packages/flask_uploads.py", line 380, in extension_allowed
celery_1   |     return ((ext in self.config.allow) or
celery_1   |   File "/usr/local/lib/python3.7/site-packages/flask_uploads.py", line 327, in config
celery_1   |     return current_app.upload_set_config[self.name]
celery_1   |   File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
celery_1   |     return getattr(self._get_current_object(), name)
celery_1   |   File "/usr/local/lib/python3.7/site-packages/werkzeug/local.py", line 307, in _get_current_object
celery_1   |     return self.__local()
celery_1   |   File "/usr/local/lib/python3.7/site-packages/flask/globals.py", line 51, in _find_app
celery_1   |     raise RuntimeError(_app_ctx_err_msg)
celery_1   | RuntimeError: Working outside of application context.
celery_1   | 
celery_1   | This typically means that you attempted to use functionality that needed
celery_1   | to interface with the current application object in some way. To solve
celery_1   | this, set up an application context with app.app_context().  See the
celery_1   | documentation for more information.

**Comment by steinitzu** [comment]
This is a flask+celery issue and has nothing to do with spoffy 
But check here in the flask docs on how to make the app context available in your tasks https://flask.palletsprojects.com/en/1.1.x/patterns/celery/
